### PR TITLE
Pass language param

### PR DESCRIPTION
**Pull request by danielglauser**
Requested work based on [this](https://github.com/democracyworks/voter-registration-works/pull/28) PR, passes along the language query param for the `/registrations` endpoint.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Since this only modifies the request when/if `language` shows up in the query params, should we just put the interceptor on the `/` route once and let the others inherit it?

**Comment by danielglauser** [comment]
@cap10morgan I'm not sure if `language` makes sense for `/status` and `/ping`. I don't think it will hurt, just doesn't make sense.

**Comment by cap10morgan** [comment]
I agree it doesn't make sense there. But due to the way bifrost works, if you put `?foo=bar` in a query string, you will have `{:foo "bar"}` in your request EDN that gets sent to the upstream component. All this interceptor does is convert the value to a keyword when the incoming key is `:language`. It's still up to the API consumer to not send inappropriate query params regardless (and they will receive schema validation errors from the upstream component if they screw it up).

**Comment by danielglauser** [comment]
@cap10morgan Let me know if this addresses your concerns.

**Comment by cap10morgan** [comment]
LGTM

**Pull request merged**
